### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [1]:
import numpy as np

In [2]:
# numpy.zeros
arr1 = np.zeros((3,2))
print(arr1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
# numpy.ones
arr2 = np.ones((5,6))
print(arr2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [4]:
# numpy.full
arr3 = np.full((3,4), 7, dtype=str)
print(arr3)

[['7' '7' '7' '7']
 ['7' '7' '7' '7']
 ['7' '7' '7' '7']]


In [5]:
# numpy.eye
arr4 = np.eye(3)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# numpy.arange
arr5 = np.arange(1,50, 5, dtype=float)
print(arr5)

[ 1.  6. 11. 16. 21. 26. 31. 36. 41. 46.]


In [7]:
# numpy.add
arr6 = np.arange(0,10,2)
arr7 = np.arange(1,11,2)
arr8 = np.add(arr6, arr7)
print(arr6)
print(arr7)
print(arr8)

[0 2 4 6 8]
[1 3 5 7 9]
[ 1  5  9 13 17]


In [8]:
# numpy.subtract
arr9 = np.subtract(arr7,arr6)
print(arr6)
print(arr7)
print(arr9)

[0 2 4 6 8]
[1 3 5 7 9]
[1 1 1 1 1]


In [9]:
# numpy.sin
arr27 = np.sin(arr6)
print(arr27)

[ 0.          0.90929743 -0.7568025  -0.2794155   0.98935825]


In [10]:
# numpy.multiply
arr10 = np.multiply(arr7, arr6)
print(arr6)
print(arr7)
print(arr10)

[0 2 4 6 8]
[1 3 5 7 9]
[ 0  6 20 42 72]


In [11]:
# numpy.sqrt
arr11 = np.array([4, 16, 56])
arr12 = np.sqrt(arr11)
print(arr12)

[2.         4.         7.48331477]


In [12]:
# numpy.dot
arr13 = np.array([[1,2,3,4],[5,7,8,4]])
arr14 = np.array([[4],[2],[1],[1]])
arr15 = np.dot(arr13, arr14)
print(arr15)

[[15]
 [46]]


In [13]:
# numpy.sum
arr16 = np.sum(arr6)
print(arr16)

20


In [14]:
# numpy.zeros_like
arr17 = np.zeros_like(arr13)
print(arr17)

[[0 0 0 0]
 [0 0 0 0]]


In [15]:
# numpy.empty_like
arr18 = np.empty_like(arr13)
print(arr18)

[[      0       1       0 5570652]
 [   1304       0     768       0]]


In [16]:
# numpy.reshape
arr19 = arr13.reshape(4, 2)
print(arr19)

[[1 2]
 [3 4]
 [5 7]
 [8 4]]


In [17]:
# numpy.isnan
arr20 = np.array([[np.NaN, 1, 8, 9, 7], [2, 6, np.NaN, 3, np.NaN]])
arr21 = np.isnan(arr20)
print(arr21)

[[ True False False False False]
 [False False  True False  True]]


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [18]:
import numpy.random as rd

In [19]:
# numpy.random.sample
arr22 = rd.sample(5)
print(arr22)

[0.63824402 0.15749552 0.10630272 0.47393888 0.17867737]


In [20]:
# numpy.random.random
arr23 = rd.random(7)
print(arr23)

[0.72019699 0.20349605 0.3348452  0.07766203 0.10356611 0.2418534
 0.38790481]


In [21]:
# numpy.random.randint
arr24 = rd.randint(7, 20, 5)
print(arr24)

[ 8 17  8 18 14]


In [22]:
# numpy.random.random_integers
arr25 = rd.random_integers(7, 20, 5)
print(arr25)

[19 17 16 19 13]


C:\Users\Dinara Akmurzina\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(7, 20 + 1) instead
  


In [23]:
# numpy.random.uniform
arr26 = rd.uniform(0, 10, 8)
print(arr26)

[3.70174295 6.1996638  1.14356163 3.87330977 0.36898263 6.034365
 2.05627244 1.04884974]


In [24]:
rd.seed()

In [25]:
# numpy.random.shuffle
print(arr19)
rd.shuffle(arr19)

[[1 2]
 [3 4]
 [5 7]
 [8 4]]


In [26]:
# numpy.random.permutation
print(arr13)
print(rd.permutation(arr13))

[[3 4 8 4]
 [5 7 1 2]]
[[5 7 1 2]
 [3 4 8 4]]


In [27]:
# numpy.random.choice
print(arr11)
print(rd.choice(arr11, 5))

[ 4 16 56]
[16 16 16  4  4]


# Прекрасная работа!