### NumPy: Введение (Часть 1) [Домашнее задание]

### Задания:

1. Установите пакет NumPy с помощью pip.

2. Пожалуйста, импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.21.5


### Ожидаемый результат
```
1.17.4
```

3. Создайте одномерный numpy.ndarray even_np, в котором он содержит четные числа только от 0 до 10.

In [2]:
# Начало вашего кода
data = []
for i in range(11):
    if i%2 == 0:
        data.append(i)
even_np = np.array(data)
# Конец вашего кода
print(even_np)

[ 0  2  4  6  8 10]


### Ожидаемый результат
```
[ 0  2  4  6  8 10]
```

4. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [3]:
# Начало вашего кода
print(even_np.ndim)
print(even_np.shape)
print(even_np.size)
print(even_np.dtype)
print(even_np.T)
# Конец вашего кода

1
(6,)
6
int32
[ 0  2  4  6  8 10]


### Ожидаемый результат
```
1
(6,)
6
int64
[ 0  2  4  6  8 10]
```

5. Создайте одномерный numpy.ndarray odd_np, в котором он содержит не четные числа только от 10 до 20, и тип элементов должен быть **комплексными числами.**

In [4]:
# Начало вашего кода
data2 = []
for i in range(10, 20):
    if i%2 != 0:
        data2.append(float(i) + 0.j)
odd_np = np.array(data2)
# Конец вашего кода
print(odd_np)

[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


### Ожидаемый результат
```
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

6. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray odd_np и распечатайте их.

In [5]:
# Начало вашего кода
print(odd_np.ndim)
print(odd_np.shape)
print(odd_np.size)
print(odd_np.dtype)
print(odd_np.T)
# Конец вашего кода

1
(5,)
5
complex128
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


### Ожидаемый результат
```
1
(5,)
5
complex128
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

# Прекрасная работа!