### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.21.5


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [2]:
# Начало вашего кода
numbers_list = []
data_1 = []
data_2 = []
for i in range(10):
    if i%2 == 0:
        data_1.append(i)
    else:
        data_2.append(i)
numbers_list.append(data_1)
numbers_list.append(data_2)
numbers = np.array(numbers_list)
# Конец вашего кода
print(numbers)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [3]:
# Начало вашего кода
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)
print(numbers.T)
# Конец вашего кода

2
(2, 5)
10
int32
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [4]:
# Начало вашего кода
overall_max = numbers.max()
overall_min = numbers.min()
overall_mean = numbers.mean()
overall_std = numbers.std()
# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [5]:
# Начало вашего кода
col_max = numbers.max(axis=0)
col_min = numbers.min(axis=0)
col_mean = numbers.mean(axis=0)
col_std = numbers.std(axis=0)
# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[1 3 5 7 9]
[0 2 4 6 8]
[0.5 2.5 4.5 6.5 8.5]
[0.5 0.5 0.5 0.5 0.5]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [6]:
# Начало вашего кода
row_max = numbers.max(axis=1, keepdims=True)
row_min = numbers.min(axis=1, keepdims=True)
row_mean = numbers.mean(axis=1, keepdims=True)
row_std = numbers.std(axis=1, keepdims=True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [7]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [8]:
# Начало вашего кода
col_mean = thd_nparr.mean(axis=0)
col_std = thd_nparr.std(axis=0)
row_mean = thd_nparr.mean(axis=1)
row_std = thd_nparr.std(axis=1)
d3_mean = thd_nparr.mean(axis=2, keepdims=True)
d3_std = thd_nparr.std(axis=2, keepdims=True)
# Конец вашего кода
print(f"Mean with respect to 0-axis\n{col_mean}")
print(f"STD with respect to 0-axis\n{col_std}")
print(f"Mean with respect to 1-axis\n{row_mean}")
print(f"STD with respect to 1-axis\n{col_std}")
print(f"Mean with respect to 2-axis\n{d3_mean}")
print(f"STD with respect to 2-axis\n{d3_std}")

Mean with respect to 0-axis
[[11. 12.]
 [13. 14.]]
STD with respect to 0-axis
[[10. 10.]
 [10. 10.]]
Mean with respect to 1-axis
[[ 2.  3.]
 [22. 23.]]
STD with respect to 1-axis
[[10. 10.]
 [10. 10.]]
Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [9]:
# ndarray.reshape()
# Начало вашего кода
print(thd_nparr.reshape(4,2))
# Конец вашего кода

[[ 1  2]
 [ 3  4]
 [21 22]
 [23 24]]


In [10]:
# ndarray.ravel()
# Начало вашего кода
print(thd_nparr.ravel())
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]


In [11]:
# ndarray.tolist()
# Начало вашего кода
print(thd_nparr.tolist())
# Конец вашего кода

[[[1, 2], [3, 4]], [[21, 22], [23, 24]]]


In [12]:
# ndarray.tofile()
# Начало вашего кода
thd_nparr.tofile("file_of_lists", sep=", ", format="%s")
# Конец вашего кода

In [13]:
# ndarray.sort()
# Начало вашего кода
unsorted_list = [[5,4,8,-3], [9,7,8,-1]]
unsorted_np = np.array(unsorted_list)
unsorted_np.sort()
print(unsorted_np)
# Конец вашего кода

[[-3  4  5  8]
 [-1  7  8  9]]


In [14]:
# ndarray.transpose()
# Начало вашего кода
print(unsorted_np.transpose())
# Конец вашего кода

[[-3 -1]
 [ 4  7]
 [ 5  8]
 [ 8  9]]


In [15]:
# ndarray.flatten()
# Начало вашего кода
copy_of_unsorted_np = unsorted_np.flatten() 
print(copy_of_unsorted_np)
# Конец вашего кода

[-3  4  5  8 -1  7  8  9]


In [16]:
# ndarray.argmin()
# Начало вашего кода
n = thd_nparr.argmin()
print(n)
# Конец вашего кода

0


In [17]:
# ndarray.argmin()
# Начало вашего кода
list_of_lists = [[[10,9],[5,4]],[[21,22],[23,24]]]

print(np.argmin(list_of_lists, axis=1))

# Конец вашего кода

[[1 1]
 [0 0]]


In [18]:
print(thd_nparr.argmin(axis=1))

[[0 0]
 [0 0]]


In [19]:
# ndarray.argmax()
# Начало вашего кода
list_of_lists = [[[10,9],[5,4]],[[21,22],[23,24]]]
print(np.argmin(list_of_lists, axis=1))
# Конец вашего кода

[[1 1]
 [0 0]]


In [20]:
print(unsorted_np.argmax(axis=0))

[1 1 1 1]


In [21]:
# ndarray.cumsum()
# Начало вашего кода
print(thd_nparr.cumsum())
# Конец вашего кода

[  1   3   6  10  31  53  76 100]


In [22]:
# ndarray.cumprod()
# Начало вашего кода
print(thd_nparr.cumprod())
# Конец вашего кода

[      1       2       6      24     504   11088  255024 6120576]


In [23]:
# ndarray.dot()
# Начало вашего кода
print(thd_nparr.dot(3))
# Конец вашего кода

[[[ 3  6]
  [ 9 12]]

 [[63 66]
  [69 72]]]


In [24]:
# ndarray.squeeze()
# Начало вашего кода
print(thd_nparr.squeeze())
# Конец вашего кода

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


In [25]:
# ndarray.repeat()
# Начало вашего кода
print(thd_nparr.repeat(5))
# Конец вашего кода

[ 1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4  4 21 21 21 21
 21 22 22 22 22 22 23 23 23 23 23 24 24 24 24 24]


# Прекрасная работа!