# Пожалуйста, выполните задачи ниже.

Вам может понадобиться больше узнать о методах, предоставляемых пакетом Numpy.

1. Создайте числовые массивы формы ```(20,5)``` со случайно сгенерированными целыми числами от 1 до 1000 (```numpy.random```). Установите ```seed=1```.

In [1]:
import numpy as np
import numpy.random as rd

In [2]:
# Начало вашего кода
rd.seed(1)
ndarr = rd.randint(1,1000, size=(20,5))
print(ndarr)
# Конец вашего кода


[[ 38 236 909  73 768]
 [906 716 646 848 961]
 [145 130 973 584 750]
 [509 391 282 179 277]
 [255 358 915 469 908]
 [253 491 669 926 399]
 [563 581 216 984 754]
 [504 479 865  87 142]
 [394   8 320 830 535]
 [314 514 897 317 210]
 [265 729 654 628 432]
 [634 457 543  72 388]
 [455 918 562 314 516]
 [965 793 498  44 589]
 [ 27 821 337 622 884]
 [298 467  16  65 197]
 [ 26 368 739 472 904]
 [283 666 617  23 778]
 [708 127 280 382 357]
 [156 934 314 596 167]]


### Ожидаемый результат:

```
[[ 38 236 909  73 768]
 [906 716 646 848 961]
 [145 130 973 584 750]
 [509 391 282 179 277]
 [255 358 915 469 908]
 [253 491 669 926 399]
 [563 581 216 984 754]
 [504 479 865  87 142]
 [394   8 320 830 535]
 [314 514 897 317 210]
 [265 729 654 628 432]
 [634 457 543  72 388]
 [455 918 562 314 516]
 [965 793 498  44 589]
 [ 27 821 337 622 884]
 [298 467  16  65 197]
 [ 26 368 739 472 904]
 [283 666 617  23 778]
 [708 127 280 382 357]
 [156 934 314 596 167]]
```

2. Каково среднее значение третьего столбца?

In [3]:
# Начало вашего кода
ndarr_mean = ndarr[:,2].mean()
print(ndarr_mean)
# Конец вашего кода

562.6


### Ожидаемый результат:

```
562.6
```

3. Каково среднее значение последних 5 строк второго и третьего столбцов?

In [4]:
# Начало вашего кода
row5_mean = ndarr[-5:,1:3].mean()
print(row5_mean)
# Конец вашего кода

452.8


### Ожидаемый результат:

```
350.4
```

4. Выберите числа из последнего столбца массива, которые больше 300 и меньше, чем 500.

In [5]:
# Начало вашего кода
last_col = ndarr[:,-1:]
filt_arr = last_col[(last_col>300) & (last_col<500)]
print(filt_arr)
# Конец вашего кода

[399 432 388 357]


### Ожидаемый результат:

```
[399 432 388 357]
```

5. Напишите функцию, которая проверяет, равен ли какой-либо из элементов данного массива numpy нулю.

In [6]:
def check_zeros(input_arr):
    # Начало вашего кода
    x = np.all(input_arr)
    if x == True:
        return False
    else:
        return True

    # Конец вашего кода
print(check_zeros(ndarr))

False


### Ожидаемый результат:

```
False
```

6. Пожалуйста, сгенерируйте массив из пяти случайных чисел из равномерного распределения.

In [7]:
# Начало вашего кода
arr_norm = rd.uniform(0, 1, 5)
# Конец вашего кода
print(arr_norm)

[0.21162812 0.26554666 0.49157316 0.05336255 0.57411761]


### Ожидаемый результат:

```
[0.21162812 0.26554666 0.49157316 0.05336255 0.57411761]
```

7. Пожалуйста, сгенерируйте массив случайных чисел формы 3х3х4 из равномерного распределения.

In [8]:
# Начало вашего кода
arr3d = rd.uniform(0,1, (3,3,4))
# Конец вашего кода
print(arr3d)

[[[0.14672857 0.58930554 0.69975836 0.10233443]
  [0.41405599 0.69440016 0.41417927 0.04995346]
  [0.53589641 0.66379465 0.51488911 0.94459476]]

 [[0.58655504 0.90340192 0.1374747  0.13927635]
  [0.80739129 0.39767684 0.1653542  0.92750858]
  [0.34776586 0.7508121  0.72599799 0.88330609]]

 [[0.62367221 0.75094243 0.34889834 0.26992789]
  [0.89588622 0.42809119 0.96484005 0.6634415 ]
  [0.62169572 0.11474597 0.94948926 0.44991213]]]


### Ожидаемый результат:

```
[[[0.14672857 0.58930554 0.69975836 0.10233443]
  [0.41405599 0.69440016 0.41417927 0.04995346]
  [0.53589641 0.66379465 0.51488911 0.94459476]]

 [[0.58655504 0.90340192 0.1374747  0.13927635]
  [0.80739129 0.39767684 0.1653542  0.92750858]
  [0.34776586 0.7508121  0.72599799 0.88330609]]

 [[0.62367221 0.75094243 0.34889834 0.26992789]
  [0.89588622 0.42809119 0.96484005 0.6634415 ]
  [0.62169572 0.11474597 0.94948926 0.44991213]]]
```

8. Пожалуйста, сгенерируйте массив случайных чисел формы 5х5 из равномерного распределения и найдите минимальное и максимальное значения.

In [9]:
# Начало вашего кода
arr2d = rd.uniform(0, 1, (5,5))
min_val = arr2d.min()
max_val = arr2d.max()
# Конец вашего кода
print(arr2d)
print(min_val)
print(max_val)

[[0.57838961 0.4081368  0.23702698 0.90337952 0.57367949]
 [0.00287033 0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124 0.92943723]
 [0.69089692 0.99732285 0.17234051 0.13713575 0.93259546]
 [0.69681816 0.06600017 0.75546305 0.75387619 0.92302454]]
0.00287032703115897
0.9973228504514805


### Ожидаемый результат:

```
[[0.57838961 0.4081368  0.23702698 0.90337952 0.57367949]
 [0.00287033 0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124 0.92943723]
 [0.69089692 0.99732285 0.17234051 0.13713575 0.93259546]
 [0.69681816 0.06600017 0.75546305 0.75387619 0.92302454]]
0.00287032703115897
0.9973228504514805
```

9. Пожалуйста, перетасуйте (```np.random```) цифры от 0 до 10 (включительно) 

In [10]:
# Начало вашего кода
arr_shuf = np.arange(0,11)
rd.shuffle(arr_shuf)
# Конец вашего кода
print(arr_shuf)

[10  3  6  1  0  4  8  5  7  2  9]


### Ожидаемый результат:

```
[10  3  6  1  0  4  8  5  7  2  9]
```

10. Пожалуйста, создайте массив (10,) случайных чисел и отсортируйте его

In [11]:
# Начало вашего кода
arr10 = rd.uniform(0, 1, 10)
arr_sort = np.sort(arr10)
# Конец вашего кода
print(arr_sort)

[0.09155644 0.10213523 0.23175846 0.23362252 0.27831884 0.28871783
 0.36784324 0.41792654 0.57006666 0.96766793]


### Ожидаемый результат:

```
[0.09155644 0.10213523 0.23175846 0.23362252 0.27831884 0.28871783
 0.36784324 0.41792654 0.57006666 0.96766793]
```

### Пожалуйста, найдите все ошибки в коде и исправьте.

Помните, что блок кодов может содержать более 1 ошибки.

11. Ожидаемый результат:

```
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]
```

In [12]:
print(np.linspace(0,21,21, endpoint=False, retstep=False))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


12. Ожидаемый результат:

```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
```

In [13]:
arr11 = np.arange(0,100)
print(arr11)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


13. Ожидаемый результат:

```
[[[[0.14672857 0.58930554 0.69975836]
   [0.10233443 0.41405599 0.69440016]]

  [[0.41417927 0.04995346 0.53589641]
   [0.66379465 0.51488911 0.94459476]]

  [[0.58655504 0.90340192 0.1374747 ]
   [0.13927635 0.80739129 0.39767684]]]


 [[[0.1653542  0.92750858 0.34776586]
   [0.7508121  0.72599799 0.88330609]]

  [[0.62367221 0.75094243 0.34889834]
   [0.26992789 0.89588622 0.42809119]]

  [[0.96484005 0.6634415  0.62169572]
   [0.11474597 0.94948926 0.44991213]]]]
```

In [14]:
print(np.resize(arr3d,(6,2,3)))

[[[0.14672857 0.58930554 0.69975836]
  [0.10233443 0.41405599 0.69440016]]

 [[0.41417927 0.04995346 0.53589641]
  [0.66379465 0.51488911 0.94459476]]

 [[0.58655504 0.90340192 0.1374747 ]
  [0.13927635 0.80739129 0.39767684]]

 [[0.1653542  0.92750858 0.34776586]
  [0.7508121  0.72599799 0.88330609]]

 [[0.62367221 0.75094243 0.34889834]
  [0.26992789 0.89588622 0.42809119]]

 [[0.96484005 0.6634415  0.62169572]
  [0.11474597 0.94948926 0.44991213]]]


14. Ожидаемый результат:

``` 
[32. 19. 25. 21. 26. 18. 22. 27. 37. 14.]

```

In [15]:
rd.seed(2)
arr1=np.ones(10)
arr2=rd.random_integers(0,40,10)
print(arr2*arr1)

[40. 15.  8. 22. 18. 11. 40.  7. 34. 31.]


C:\Users\Dinara Akmurzina\.conda\envs\py37\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(0, 40 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


15. Ожидаемый результат:

``` 
[[2.32624478 2.99713989 2.11483556 2.3372708  4.24467882]]

```

In [16]:
arr1=np.resize(arr1, (1,5))
arr3=np.dot(arr1, arr2d)
print(arr3)

[[2.32624478 2.99713989 2.11483556 2.3372708  4.24467882]]


# Прекрасная работа!